Sajawal/grid/implementation
Sajawal-dev1/task-to-do pull request #11
Opened 2023-02-06 10:50 UTC by Sajawal-dev1

Grid implementation

2023-02-06 13:04 UTC, IshfaqAhmedAwan requested changes

2023-02-06 13:04 UTC, IshfaqAhmedAwan commented on package.json
> +    "@material-ui/core": "^4.12.4",
Why are we using material-ui when we are already using mui

2023-02-06 13:04 UTC, IshfaqAhmedAwan commented on src/components/AddTaskField.js
> +    <Box className={classes.top}>
Can we use card instead of box here

2023-02-06 13:04 UTC, IshfaqAhmedAwan commented on src/components/TodoInputs.js
> +        label={placeholder}
name it label instead of placeholder

2023-02-06 13:04 UTC, IshfaqAhmedAwan commented on src/components/AddTaskField.js
> +    width: "-webkit-fill-available",
Why are we using width multiple time here

2023-02-06 14:08 UTC, Sajawal-dev1 commented on src/components/AddTaskField.js
> +    <Box className={classes.top}>
I can but the way I implemented Grid there will be many changes require to implement card 
but If you want I will do it for you

2023-02-07 07:27 UTC, IshfaqAhmedAwan commented on src/components/AddTaskField.js
> +    <Box className={classes.top}>
OK got it

2023-02-07 07:34 UTC, IshfaqAhmedAwan commented on src/components/TaskFeatures.js
> +    width: "90%",
we should avoid percentage widths

2023-02-08 11:18 UTC, ahmadfaraz629 commented on src/components/CommonComponents/TodoIconButtons.js
> +export default TodoIconButtons;
<img width="349" alt="image" src="https://user-images.githubusercontent.com/17162601/217514458-6392657d-5341-4b9b-aad7-04b5d98b3619.png">
 Fix this EOF issue.

2023-02-08 11:18 UTC, ahmadfaraz629 commented on src/components/CommonComponents/TodoButtons.js
> +const TodoButtons = ({ onClick, className, value }) => {
Rename this to Button

2023-02-08 11:18 UTC, ahmadfaraz629 commented on src/components/CommonComponents/TodoIconButtons.js
> +const TodoIconButtons = ({ onClick, className, value }) => {
rename this to IconButton

2023-02-08 11:18 UTC, ahmadfaraz629 commented on src/components/CommonComponents/TodoIconButtons.js
> +import { IconButton } from "@mui/material";
to avoid confusion you can import this as 

import { IconButton as MuButton } from "@mui/material";

2023-02-08 11:18 UTC, ahmadfaraz629 commented on src/components/CommonComponents/TodoInputs.js
> +const TodoInput = ({
Change this name to Input or TextField

2023-02-09 11:55 UTC, IshfaqAhmedAwan requested changes

2023-02-09 11:55 UTC, IshfaqAhmedAwan commented on src/components/TaskFeatures.js
> +                setCheckEditField(!checkEditField);
name it setShowEditField

2023-02-09 11:55 UTC, IshfaqAhmedAwan commented on src/components/TaskFeatures.js
> +  const {id,name:title,completed} = todo;
move constants before the functions

2023-02-09 11:55 UTC, IshfaqAhmedAwan commented on src/components/TasksList.js
> +  useEffect(() => {
separate useEffect and constants by empty line

2023-02-09 12:54 UTC, merged