Css added
Sajawal-dev1/task-to-do pull request #3
Opened 2023-01-20 10:22 UTC by Sajawal-dev1

CSS and empty input box Done

2023-01-20 10:55 UTC, alitjanjua requested changes

2023-01-20 10:55 UTC, alitjanjua commented on src/AddTodo.css
> +.btn-sub{
name of these kind of files should start with lower case letter.
e.g. `addToDo.css`

2023-01-20 10:55 UTC, alitjanjua commented on src/AddTodo.css
> +
remove empty lines

2023-01-20 10:55 UTC, alitjanjua commented on src/AddTodo.css
> +  }
add eof here

2023-01-20 10:55 UTC, alitjanjua commented on src/App.css
> +.task-input{
if you've created task related separate css file then you don't have to add that css here too.

2023-01-20 10:55 UTC, alitjanjua commented on src/App.css
> +}
add eof here

2023-01-20 10:55 UTC, alitjanjua commented on src/App.js
> +import AddTodo from './components/AddTodo';
components name should be more meaningful and sensible.
```suggestion
import AddTaskField from './components/AddTaskField';
```

2023-01-20 10:55 UTC, alitjanjua commented on src/App.js
> +import TodoList from './components/TodoList';
```suggestion
import TasksList from './components/TasksList';
```

2023-01-20 10:55 UTC, alitjanjua commented on src/App.js
> +		<div className="app">
indentation is not correct.
there should be 2 space indentation enabled.

2023-01-20 10:55 UTC, alitjanjua commented on src/components/AddTodo.js
> +import { addTask } from "../redux/tasksSlice";
always use absolute paths
```suggestion
import { addTask } from "store/redux/tasksSlice";
```

2023-01-20 10:55 UTC, alitjanjua commented on src/components/AddTodo.js
> +
use empty lines from everywhere

2023-01-20 10:55 UTC, alitjanjua commented on src/components/AddTodo.js
> +			<input className='task-input'
you still haven't used react-hook-form for fields. Do that

2023-01-20 10:55 UTC, alitjanjua commented on src/components/TodoItem.js
> +		console.log(newval)
remove all console statements

2023-01-20 10:55 UTC, alitjanjua commented on src/components/TodoList.js
> +export default TodoList;
add eof

2023-01-20 10:55 UTC, alitjanjua commented on src/redux/tasksSlice.js
> +import "../App.css";
use absolute paths

2023-01-20 10:55 UTC, alitjanjua commented on src/redux/tasksSlice.js
> +import "../App.css";
```suggestion
import "App.css";
```

2023-01-20 10:55 UTC, alitjanjua commented on src/redux/tasksSlice.js
> +             let a=0;
use meaningful names for variables.

2023-01-23 09:42 UTC, alitjanjua requested changes

2023-01-23 09:42 UTC, alitjanjua commented on src/redux/tasksSlice.js
> +import "../App.css";
@Sajawal-dev1 this has not been resolved.

2023-01-26 07:10 UTC, closed without merging

2023-01-26 07:11 UTC, Sajawal-dev1 commented
No need

2023-01-26 07:11 UTC, Sajawal-dev1 commented
No more need